include: package:lint/analysis_options.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - lib/gen/*.dart
    - lib/generated_plugin_registrant.dart
    - lib/**/*.g.dart
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    unawaited_futures: true
    prefer_single_quotes: true
    avoid_positional_boolean_parameters: false

dart_code_metrics:
  rules:
    - prefer-trailing-comma
  metrics:
    cyclomatic-complexity: 1000
    maximum-nesting-level: 1000
    number-of-parameters: 1000
    number-of-methods: 1000
    source-lines-of-code: 1000
  metrics-exclude:
    - lib/screens/**
    - lib/widgets/**
